# Preprocessing of Neighbourhoods File

In [2]:
import pandas as pd
import numpy as np
# from prep_functions import missing_info

In [3]:
listings_simple = pd.read_csv('../Data/listings_simple.csv')
listings_simple.info()
listings_simple.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7921 entries, 0 to 7920
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              7921 non-null   int64
 1   name                            7921 non-null   object
 2   host_id                         7921 non-null   int64
 3   host_name                       7911 non-null   object
 4   neighbourhood_group             7921 non-null   object
 5   neighbourhood                   7921 non-null   object
 6   latitude                        7921 non-null   float64
 7   longitude                       7921 non-null   float64
 8   room_type                       7921 non-null   object
 9   price                           7017 non-null   float64
 10  minimum_nights                  7921 non-null   int64
 11  number_of_reviews               7921 non-null   int64
 12  last_review                     7147 non-null   object
 13  reviews_per_month               7147 non-null   float64
 14  calculated_host_listings_count  7921 non-null   int64
 15  availability_365                7921 non-null   int64
 16  number_of_reviews_ltm           7921 non-null   int64
 17  license                         7295 non-null   object
dtypes: float64(4), int64(7), object(7)
memory usage: 1.1+ MB

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,6624,Venice garden charme and canal view!,15016,Francesca,Isole,Santa Croce,45.43977,12.32736,Entire home/apt,227.0,4,89,2025-02-16,0.54,1,341,1,"I applied for a CIN, but haven’t received it yet"
1,27116,Junior Suite with balcony overlooking canal,116144,Giò&Giò,Isole,San Marco,45.43277,12.33456,Private room,187.0,1,414,2022-11-11,2.33,3,125,0,IT027042B4RZ8EK8UI
2,44527,Luxury Historic Apartment on Calm Sunny Canal,120215,Marc & Elisabeth,Isole,Cannaregio,45.44569,12.32902,Entire home/apt,391.0,2,149,2024-12-31,0.88,2,287,18,IT027042B4GR0PSZS4
3,47383,Ca' Barba B&B: room n102 (jacuzzi shower),214390,Alessandro,Isole,San Polo,45.43921,12.33310,Hotel room,98.0,2,408,2025-02-10,2.32,4,316,25,IT027042B4D3D4AUUS
4,49656,Ca' Foscari Apartment,226598,Andrea,Isole,Dorsoduro,45.43549,12.32612,Entire home/apt,101.0,3,131,2025-02-03,0.87,2,249,18,IT027042C2L6NZYNJR

In [4]:
listings = pd.read_csv('../Data/listings.csv')
listings.info()
listings.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7921 entries, 0 to 7920
Data columns (total 79 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            7921 non-null   int64
 1   listing_url                                   7921 non-null   object
 2   scrape_id                                     7921 non-null   int64
 3   last_scraped                                  7921 non-null   object
 4   source                                        7921 non-null   object
 5   name                                          7921 non-null   object
 6   description                                   7705 non-null   object
 7   neighborhood_overview                         4489 non-null   object
 8   picture_url                                   7920 non-null   object
 9   host_id                                       7921 non-null   int64
 10  host_url                                      7921 non-null   object
 11  host_name                                     7911 non-null   object
 12  host_since                                    7911 non-null   object
 13  host_location                                 5977 non-null   object
 14  host_about                                    4238 non-null   object
 15  host_response_time                            7057 non-null   object
 16  host_response_rate                            7057 non-null   object
 17  host_acceptance_rate                          7471 non-null   object
 18  host_is_superhost                             7627 non-null   object
 19  host_thumbnail_url                            7911 non-null   object
 20  host_picture_url                              7911 non-null   object
 21  host_neighbourhood                            3800 non-null   object
 22  host_listings_count                           7911 non-null   float64
 23  host_total_listings_count                     7911 non-null   float64
 24  host_verifications                            7911 non-null   object
 25  host_has_profile_pic                          7911 non-null   object
 26  host_identity_verified                        7911 non-null   object
 27  neighbourhood                                 4489 non-null   object
 28  neighbourhood_cleansed                        7921 non-null   object
 29  neighbourhood_group_cleansed                  7921 non-null   object
 30  latitude                                      7921 non-null   float64
 31  longitude                                     7921 non-null   float64
 32  property_type                                 7921 non-null   object
 33  room_type                                     7921 non-null   object
 34  accommodates                                  7921 non-null   int64
 35  bathrooms                                     7015 non-null   float64
 36  bathrooms_text                                7915 non-null   object
 37  bedrooms                                      7768 non-null   float64
 38  beds                                          7009 non-null   float64
 39  amenities                                     7921 non-null   object
 40  price                                         7017 non-null   object
 41  minimum_nights                                7921 non-null   int64
 42  maximum_nights                                7921 non-null   int64
 43  minimum_minimum_nights                        7921 non-null   int64
 44  maximum_minimum_nights                        7921 non-null   int64
 45  minimum_maximum_nights                        7921 non-null   int64
 46  maximum_maximum_nights                        7921 non-null   int64
 47  minimum_nights_avg_ntm                        7921 non-null   float64
 48  maximum_nights_avg_ntm                        7921 non-null   float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              7780 non-null   object
 51  availability_30                               7921 non-null   int64
 52  availability_60                               7921 non-null   int64
 53  availability_90                               7921 non-null   int64
 54  availability_365                              7921 non-null   int64
 55  calendar_last_scraped                         7921 non-null   object
 56  number_of_reviews                             7921 non-null   int64
 57  number_of_reviews_ltm                         7921 non-null   int64
 58  number_of_reviews_l30d                        7921 non-null   int64
 59  availability_eoy                              7921 non-null   int64
 60  number_of_reviews_ly                          7921 non-null   int64
 61  estimated_occupancy_l365d                     7921 non-null   int64
 62  estimated_revenue_l365d                       7017 non-null   float64
 63  first_review                                  7147 non-null   object
 64  last_review                                   7147 non-null   object
 65  review_scores_rating                          7147 non-null   float64
 66  review_scores_accuracy                        7147 non-null   float64
 67  review_scores_cleanliness                     7147 non-null   float64
 68  review_scores_checkin                         7147 non-null   float64
 69  review_scores_communication                   7147 non-null   float64
 70  review_scores_location                        7146 non-null   float64
 71  review_scores_value                           7147 non-null   float64
 72  license                                       7295 non-null   object
 73  instant_bookable                              7921 non-null   object
 74  calculated_host_listings_count                7921 non-null   int64
 75  calculated_host_listings_count_entire_homes   7921 non-null   int64
 76  calculated_host_listings_count_private_rooms  7921 non-null   int64
 77  calculated_host_listings_count_shared_rooms   7921 non-null   int64
 78  reviews_per_month                             7147 non-null   float64
dtypes: float64(19), int64(24), object(36)
memory usage: 4.8+ MB

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,6624,https://www.airbnb.com/rooms/6624,20250302033917,2025-03-02,city scrape,Venice garden charme and canal view!,I'm thrilled to share my apartment with garden...,We are in the middle of a residential area cal...,https://a0.muscache.com/pictures/65440024/a564...,15016,...,4.88,4.95,4.92,"I applied for a CIN, but haven’t received it yet",f,1,1,0,0,0.54
1,27116,https://www.airbnb.com/rooms/27116,20250302033917,2025-03-02,city scrape,Junior Suite with balcony overlooking canal,"Few steps from Saint Mark square, on a picture...","The area is very beautiful and characteristic,...",https://a0.muscache.com/pictures/miso/Hosting-...,116144,...,4.81,4.94,4.78,IT027042B4RZ8EK8UI,t,3,1,2,0,2.33
2,44527,https://www.airbnb.com/rooms/44527,20250302033917,2025-03-02,city scrape,Luxury Historic Apartment on Calm Sunny Canal,An apartment that blends Gothic style with ini...,"Cannaregio is a well-connected, truly Venetian...",https://a0.muscache.com/pictures/d81fb136-a867...,120215,...,4.94,4.91,4.71,IT027042B4GR0PSZS4,f,2,2,0,0,0.88
3,47383,https://www.airbnb.com/rooms/47383,20250302033917,2025-03-02,city scrape,Ca' Barba B&B: room n102 (jacuzzi shower),"Ca' Barb B&B, a few steps away from Rialto bri...",San Polo is highly rated by guests for walking...,https://a0.muscache.com/pictures/550179/3b2f0d...,214390,...,4.98,4.94,4.88,IT027042B4D3D4AUUS,t,4,1,0,0,2.32
4,49656,https://www.airbnb.com/rooms/49656,20250302033917,2025-03-02,city scrape,Ca' Foscari Apartment,It’s a lovely quiet newly restored flat within...,The apartment is on the first floor (second fl...,https://a0.muscache.com/pictures/41037529-8487...,226598,...,4.97,4.97,4.78,IT027042C2L6NZYNJR,t,2,2,0,0,0.87

In [5]:
print(listings_simple.keys().isin(listings.keys()))
print(listings_simple.keys())

# the missing column 'neighbourhood_group' is existing in the listings df, but under the name 'neighbourhood_group_cleansed'

[ True  True  True  True False  True  True  True  True  True  True  True
  True  True  True  True  True  True]
Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license'],
      dtype='object')

In [6]:
def missing_info(df, id_column, sort_clmn, sort_ascending=False):
    """ 
    returns Dataframe which shows information about missing values
    for eacht column of the Dataframe
    """

    missing_info = []

    for col in df.columns:
        missing_rows = df[df[col].isnull()]
        num_missing = missing_rows.shape[0]

        row_ids = missing_rows[id_column].tolist()
        percent_missing = round((num_missing/df.shape[0])*100, 2)
        dtype = df[col].dtype
        missing_info.append({
            'column': col,
            'dtype': str(dtype),
            'num_missing': num_missing,
            'percent_missing': percent_missing,
            'affected_row_ids': row_ids
        })

    missing_df = pd.DataFrame(missing_info)
    missing_df = missing_df.sort_values(by=sort_clmn, ascending=sort_ascending)
    missing_df = missing_df.reset_index(drop=True)
    return missing_df

In [19]:
missing_df = missing_info(listings, 'id', 'column', False)
missing_df

,column,dtype,num_missing,percent_missing,affected_row_ids
0,source,object,0,0.00,[]
1,scrape_id,int64,0,0.00,[]
2,room_type,object,0,0.00,[]
3,reviews_per_month,float64,740,9.52,"[1482860, 2014854, 3118010, 6782983, 7018697, ..."
4,review_scores_value,float64,740,9.52,"[1482860, 2014854, 3118010, 6782983, 7018697, ..."
...,...,...,...,...,...
66,availability_60,int64,0,0.00,[]
67,availability_365,int64,0,0.00,[]
68,availability_30,int64,0,0.00,[]
69,amenities,object,0,0.00,[]
70,accommodates,int64,0,0.00,[]

In [24]:
listings['last_review'].unique()

array(['2025-02-16', '2022-11-11', '2024-12-31', '2025-02-10',
       '2025-02-03', '2023-05-06', '2017-05-11', '2025-01-24',
       '2018-03-12', '2025-02-08', '2024-12-30', '2025-02-24',
       '2025-02-28', '2024-10-28', '2023-11-17', '2025-02-23',
       '2022-10-13', '2024-12-27', '2025-01-30', '2024-09-24',
       '2024-05-26', '2024-12-02', '2024-10-27', '2025-02-12',
       '2025-02-14', '2024-04-22', '2024-10-03', '2024-10-24',
       '2025-02-04', '2024-09-30', '2024-10-30', '2025-02-22',
       '2024-11-02', '2024-11-04', '2025-02-17', '2025-01-03',
       '2025-02-26', '2024-09-05', '2022-05-30', '2024-07-31',
       '2024-11-17', '2025-01-04', '2025-02-25', '2024-12-28',
       '2025-02-09', '2024-10-14', '2024-09-06', '2024-10-29',
       '2024-12-24', '2025-01-05', '2024-12-29', '2025-01-09',
       '2025-02-18', '2025-02-27', '2024-01-03', '2022-05-07',
       '2020-04-28', '2024-10-17', '2025-01-26', '2024-10-13',
       '2024-10-12', '2020-02-17', '2025-03-01', '2025-02-19',
       '2024-09-23', '2023-10-02', '2024-08-31', '2024-08-27',
       '2024-11-18', '2023-11-19', '2024-11-24', '2024-09-03',
       '2022-05-27', '2025-02-02', '2024-09-20', '2024-05-30',
       '2023-09-23', '2024-09-02', '2025-01-10', '2025-02-01',
       '2025-02-13', '2024-10-20', '2024-10-21', '2024-11-25',
       '2025-01-06', '2024-10-10', '2025-01-31', '2024-11-03',
       '2025-01-01', '2023-09-21', '2024-04-19', '2016-03-29',
       '2024-07-22', '2024-06-11', '2024-01-25', '2025-01-08',
       '2022-10-15', '2025-01-22', '2024-08-23', '2022-09-12',
       '2022-09-05', '2022-07-24', '2022-08-26', '2019-10-09',
       '2024-10-04', '2024-11-08', '2021-11-29', '2024-10-07',
       '2024-09-14', '2024-11-05', '2023-06-04', '2025-02-07',
       '2022-10-23', '2024-11-19', '2024-01-01', '2024-11-30',
       '2020-02-23', '2024-09-01', '2025-01-02', '2025-02-15',
       '2025-01-20', '2024-10-15', '2024-10-16', '2013-07-21',
       '2024-07-02', '2024-12-26', '2020-10-10', '2022-05-02',
       '2024-09-11', '2019-09-20', '2025-01-21', '2024-11-01',
       '2022-07-05', '2021-10-27', '2025-01-18', '2024-09-08',
       '2024-04-20', '2024-07-30', '2024-06-28', '2024-08-21',
       '2024-02-14', '2021-08-10', '2024-08-14', '2023-07-09',
       '2023-07-03', '2025-02-21', nan, '2017-06-25', '2024-04-18',
       '2024-12-07', '2025-01-16', '2024-10-31', '2019-10-07',
       '2023-11-09', '2024-05-20', '2024-11-12', '2024-10-23',
       '2017-12-21', '2024-06-08', '2024-06-16', '2024-11-29',
       '2024-12-06', '2023-10-08', '2025-02-20', '2024-11-10',
       '2024-11-16', '2024-09-22', '2024-10-11', '2024-06-12',
       '2024-07-14', '2024-07-01', '2023-10-28', '2024-12-23',
       '2022-11-12', '2024-10-26', '2022-12-19', '2025-01-07',
       '2024-08-24', '2024-09-26', '2023-02-27', '2016-10-07',
       '2024-11-23', '2023-05-01', '2025-01-27', '2014-09-15',
       '2024-11-28', '2024-09-29', '2024-07-13', '2024-05-31',
       '2022-04-08', '2018-05-14', '2024-05-11', '2024-10-05',
       '2023-07-08', '2024-11-20', '2024-06-10', '2024-12-22',
       '2022-09-20', '2023-09-04', '2022-09-06', '2024-11-11',
       '2024-09-15', '2024-12-03', '2025-01-19', '2018-09-08',
       '2024-11-13', '2024-04-11', '2024-08-11', '2020-08-15',
       '2019-07-28', '2024-05-17', '2024-12-16', '2018-05-28',
       '2021-10-30', '2024-07-12', '2019-11-11', '2024-09-16',
       '2023-10-29', '2024-05-27', '2025-01-12', '2024-12-17',
       '2024-05-12', '2024-05-06', '2024-08-10', '2019-06-11',
       '2024-10-18', '2024-06-06', '2020-01-03', '2019-10-06',
       '2022-08-08', '2021-07-24', '2024-07-17', '2021-08-31',
       '2022-09-19', '2021-10-31', '2024-05-07', '2024-12-08',
       '2015-04-23', '2024-11-09', '2024-05-22', '2023-03-01',
       '2024-10-09', '2022-07-31', '2024-05-18', '2018-10-27',
       '2024-10-06', '2023-10-15', '2019-07-11', '2024-07-15',
       '2017-11-23', '2024-04-27', '2021-08-27', '2025-02-11',
       '2019-10-27', '2019-09-23', '2024-11-06', '2024-07-20',
       '2024-09-21', '2024-04-25', '2024-07-21', '2024-12-09',
       '2023-10-20', '2023-09-18', '2024-09-04', '2024-06-24',
       '2022-11-20', '2024-10-19', '2024-06-22', '2017-08-26',
       '2024-10-02', '2024-05-16', '2024-08-19', '2024-07-27',
       '2024-05-04', '2015-09-25', '2024-08-28', '2024-07-04',
       '2018-01-01', '2021-09-11', '2018-07-17', '2017-10-31',
       '2024-11-22', '2024-09-27', '2025-02-05', '2024-05-13',
       '2019-09-21', '2024-08-13', '2019-11-23', '2023-06-15',
       '2023-10-30', '2024-07-16', '2025-01-25', '2023-10-23',
       '2023-05-08', '2020-01-04', '2024-12-18', '2016-01-02',
       '2019-06-25', '2018-09-30', '2018-05-27', '2022-08-31',
       '2025-01-11', '2024-08-16', '2021-02-25', '2023-11-28',
       '2023-05-24', '2024-09-17', '2024-12-12', '2023-08-15',
       '2023-10-14', '2025-01-17', '2024-10-25', '2019-10-12',
       '2022-10-03', '2023-01-04', '2024-08-12', '2023-04-26',
       '2019-10-20', '2024-06-15', '2019-07-05', '2024-11-15',
       '2024-06-29', '2018-11-04', '2020-08-30', '2023-06-23',
       '2024-09-25', '2023-06-16', '2022-10-16', '2024-10-22',
       '2019-08-02', '2019-11-03', '2019-12-01', '2018-10-02',
       '2024-10-01', '2021-11-04', '2024-12-01', '2020-01-10',
       '2022-11-04', '2022-07-11', '2024-06-18', '2020-08-29',
       '2023-11-03', '2021-10-09', '2023-05-23', '2019-12-18',
       '2024-08-02', '2017-07-03', '2016-08-13', '2022-10-04',
       '2021-09-27', '2024-07-06', '2019-09-03', '2020-02-28',
       '2018-05-25', '2016-09-26', '2023-07-25', '2024-07-11',
       '2023-05-29', '2024-11-07', '2024-08-03', '2023-02-18',
       '2023-10-22', '2022-06-27', '2024-11-27', '2024-12-05',
       '2017-07-21', '2022-06-02', '2017-08-14', '2020-08-07',
       '2023-09-29', '2024-12-25', '2025-01-23', '2024-12-21',
       '2024-08-18', '2024-08-30', '2025-02-06', '2023-07-28',
       '2017-01-02', '2024-12-04', '2017-06-18', '2018-09-26',
       '2024-07-24', '2025-01-29', '2025-01-28', '2024-02-25',
       '2024-06-20', '2023-11-30', '2023-06-03', '2024-12-10',
       '2023-09-25', '2023-11-04', '2023-03-30', '2024-12-13',
       '2024-02-12', '2023-09-14', '2021-11-01', '2023-07-17',
       '2016-12-29', '2024-09-28', '2017-10-12', '2022-08-13',
       '2019-02-18', '2024-07-03', '2023-09-27', '2024-10-08',
       '2019-09-06', '2021-10-24', '2019-11-04', '2022-10-26',
       '2024-07-26', '2023-01-01', '2020-02-19', '2025-01-14',
       '2024-06-02', '2024-08-22', '2023-08-28', '2018-02-08',
       '2018-09-29', '2019-01-01', '2018-05-01', '2019-05-18',
       '2024-11-26', '2020-08-06', '2020-10-16', '2024-05-15',
       '2024-01-02', '2025-01-13', '2022-06-30', '2022-10-02',
       '2024-04-28', '2019-08-18', '2024-05-25', '2019-06-30',
       '2019-06-26', '2017-11-27', '2021-07-15', '2018-10-28',
       '2019-10-28', '2024-08-01', '2023-10-24', '2023-10-16',
       '2022-02-27', '2022-04-18', '2023-05-21', '2023-05-22',
       '2023-12-27', '2024-08-04', '2024-05-21', '2023-05-25',
       '2024-12-14', '2020-10-12', '2024-07-18', '2022-09-04',
       '2020-02-29', '2022-07-17', '2019-05-09', '2024-09-18',
       '2023-01-21', '2023-11-26', '2023-09-12', '2024-06-03',
       '2023-02-23', '2024-11-14', '2023-10-31', '2023-10-06',
       '2018-10-09', '2024-07-29', '2019-09-29', '2024-05-10',
       '2024-06-17', '2024-09-07', '2024-08-07', '2021-08-26',
       '2022-11-05', '2020-01-05', '2024-04-29', '2023-08-21',
       '2024-02-10', '2022-11-09', '2023-11-05', '2023-10-09',
       '2023-11-23', '2024-08-25', '2024-08-15', '2018-09-24',
       '2021-10-10', '2018-09-19', '2023-10-26', '2021-09-26',
       '2023-05-19', '2021-09-29', '2020-10-25', '2024-02-01',
       '2024-03-25', '2023-10-17', '2024-06-21', '2018-10-30',
       '2024-05-14', '2023-08-19', '2024-09-13', '2024-12-20',
       '2018-09-05', '2023-01-30', '2022-08-07', '2024-11-21',
       '2022-10-06', '2018-11-30', '2018-08-17', '2023-01-10',
       '2018-10-29', '2019-10-11', '2019-08-07', '2024-09-19',
       '2022-11-02', '2022-05-28', '2018-09-09', '2024-07-05',
       '2024-12-19', '2022-09-08', '2024-05-24', '2019-09-18',
       '2021-08-16', '2023-09-03', '2018-12-23', '2019-04-05',
       '2024-05-03', '2023-08-07', '2019-06-02', '2023-11-01',
       '2020-01-31', '2025-01-15', '2024-07-23', '2019-09-15',
       '2021-08-29', '2024-09-10', '2023-08-17', '2024-07-09',
       '2024-06-23', '2023-06-02', '2023-07-13', '2024-06-09',
       '2022-06-19', '2024-06-14', '2023-09-09', '2024-03-20',
       '2023-08-13', '2023-10-07', '2023-11-14', '2023-06-18',
       '2023-06-25', '2020-08-22', '2019-09-11', '2021-05-28',
       '2022-05-31', '2020-07-30', '2024-04-04', '2023-01-02',
       '2024-09-09', '2022-09-30', '2019-10-30', '2024-08-26',
       '2023-11-06', '2023-10-19', '2023-09-10', '2023-09-19',
       '2023-10-01', '2019-08-19', '2022-07-19', '2023-04-02',
       '2023-07-15', '2022-09-28', '2024-04-21', '2022-06-15',
       '2021-11-02', '2023-09-06', '2023-04-25', '2020-02-27',
       '2019-08-29', '2019-07-24', '2023-07-27', '2022-04-15',
       '2019-10-21', '2023-12-31', '2023-06-29', '2023-12-29',
       '2024-08-17', '2024-12-15', '2021-10-15', '2022-04-21',
       '2022-01-02', '2020-02-26', '2022-06-18', '2021-11-27',
       '2022-07-22', '2024-03-29', '2025-03-02', '2022-10-18',
       '2023-12-20', '2022-12-03', '2022-09-26', '2024-04-24',
       '2022-10-25', '2022-06-04', '2022-09-10', '2023-12-03',
       '2024-07-07', '2024-04-01', '2023-09-30', '2024-09-12',
       '2023-02-25', '2022-05-11', '2024-03-27', '2021-11-24',
       '2022-09-07', '2021-11-12', '2023-05-14', '2022-04-27',
       '2020-09-08', '2022-11-28', '2022-11-10', '2024-03-22',
       '2023-01-25', '2024-08-29', '2023-05-15', '2022-11-18',
       '2022-08-01', '2024-04-16', '2020-08-21', '2024-05-09',
       '2024-01-24', '2020-07-05', '2022-06-07', '2024-07-25',
       '2024-08-08', '2023-11-10', '2024-03-12', '2024-08-05',
       '2023-09-24', '2023-07-05', '2022-10-28', '2023-05-30',
       '2024-04-17', '2022-09-29', '2024-04-14', '2022-03-01',
       '2022-07-16', '2021-12-30', '2021-09-17', '2022-08-15',
       '2021-11-10', '2022-01-04', '2021-08-08', '2023-12-26',
       '2023-07-18', '2021-09-18', '2024-06-01', '2023-04-03',
       '2024-03-31', '2022-04-26', '2024-04-13', '2022-11-01',
       '2024-01-07', '2022-07-20', '2023-06-05', '2024-05-05',
       '2023-04-08', '2024-03-26', '2023-11-02', '2021-12-29',
       '2023-10-05', '2024-07-08', '2022-02-12', '2024-05-08',
       '2022-01-01', '2023-05-28', '2023-09-17', '2022-12-15',
       '2021-11-07', '2021-10-19', '2023-12-15', '2022-05-26',
       '2022-07-14', '2022-01-13', '2022-05-17', '2023-12-25',
       '2023-04-23', '2022-08-18', '2023-05-20', '2023-06-24',
       '2023-10-27', '2023-06-08', '2024-07-10', '2023-07-29',
       '2023-05-11', '2023-08-05', '2022-04-17', '2023-08-02',
       '2022-12-28', '2023-12-10', '2024-02-13', '2024-04-07',
       '2022-09-14', '2024-02-24', '2022-10-09', '2023-08-11',
       '2023-11-13', '2024-07-28', '2022-10-05', '2024-01-22',
       '2022-10-17', '2022-10-22', '2023-02-20', '2022-09-23',
       '2023-08-20', '2023-02-16', '2022-11-21', '2023-04-30',
       '2023-02-21', '2024-03-15', '2023-10-03', '2022-11-26',
       '2024-06-30', '2023-07-19', '2024-03-08', '2024-02-11',
       '2023-07-01', '2024-01-11', '2023-02-11', '2023-04-28',
       '2023-02-19', '2023-05-16', '2023-09-15', '2023-06-30',
       '2023-08-06', '2024-03-30', '2024-12-11', '2023-07-23',
       '2023-07-14', '2024-06-26', '2023-05-07', '2023-11-27',
       '2023-07-26', '2023-10-04', '2024-08-09', '2023-12-19',
       '2023-07-20', '2023-06-13', '2023-07-02', '2024-05-02',
       '2024-05-23', '2024-04-05', '2024-03-03', '2024-06-05',
       '2024-03-14', '2024-06-13', '2024-08-20', '2024-04-30',
       '2024-04-23', '2024-04-15', '2024-03-18', '2024-04-12',
       '2024-04-02', '2024-06-04', '2024-05-29', '2024-08-06'],
      dtype=object)

## delete columns whith to many missing values or which will not be used

In [14]:
delet_columns = [
    'calendar_updated', 'host_neighbourhood', 'host_about', 'neighbourhood', 
    'neighborhood_overview', 'host_location', 'estimated_revenue_l365d', 'last_scraped'
    ]

listings = listings.drop(delet_columns, axis=1)

## Deleting Rows based on missing values

In [15]:
def shared_values(column1, column2):
    clmn1_ids = missing_df[missing_df['column'] == column1]['affected_row_ids'].values[0]
    clmn2_ids = missing_df[missing_df['column'] == column2]['affected_row_ids'].values[0]

    shared = list(set(clmn1_ids) & set(clmn2_ids))
    return shared

### Beds and Bedrooms

In [16]:
print(listings[['beds', 'bedrooms']])
print('unique bed vals:', listings['beds'].unique())
print('unique bedroom vals:', listings['bedrooms'].unique())

      beds  bedrooms
0      6.0       2.0
1      2.0       1.0
2      3.0       3.0
3      1.0       1.0
4      2.0       2.0
...    ...       ...
7916   3.0       1.0
7917   6.0       4.0
7918   4.0       4.0
7919   1.0       1.0
7920   2.0       1.0

[7921 rows x 2 columns]
unique bed vals: [ 6.  2.  3.  1. nan  4.  5.  7.  0.  8.  9. 12. 11. 13. 10. 15.]
unique bedroom vals: [ 2.  1.  3. nan  7.  5.  4.  0.  6.  8. 10. 14. 11. 17. 20.]

In [17]:
shared_ids = shared_values('beds', 'bedrooms')
length = len(shared_ids)
length, (length/listings.shape[0])*100

(151, 1.906324958969827)

In [18]:
# delet all rows with missing num of bed and num of bedrooms
listings = listings[~listings['id'].isin(shared_ids)]

In [236]:
# caluculate average Beds per Bedroom
bed_filtered_listings = listings.dropna(subset=['beds', 'bedrooms'])
avg_beds_per_bedroom = bed_filtered_listings['beds'].sum() / bed_filtered_listings['bedrooms'].sum()
avg_beds_per_bedroom

1.48927577851566

In [237]:
def calc_distribution(fix_value, of_column, to_column, df):
    
    # print(f'Probabilities for {to_column} given {of_column}={fix_value}\n')

    # remove rows with null values
    filtered_df = df.dropna(subset=[of_column, to_column])
    filtered_df = filtered_df[filtered_df[of_column] == fix_value]
    # print(filtered_df)

    # frequency of each unique ratio
    frequency = filtered_df[to_column].value_counts()

    # calc probabilities
    tot = frequency.sum()
    probability = frequency / tot
    distribution_df = pd.DataFrame({to_column: frequency.index, 'Probability': probability.values})
    # print(distribution_df)
    return distribution_df

In [238]:
calc_distribution(1.,'beds', 'bedrooms', listings)

   bedrooms  Probability
0       1.0     0.947175
1       0.0     0.027102
2       2.0     0.020211
3       3.0     0.004134
4       7.0     0.000919
5       4.0     0.000459

In [239]:
def distribution_imputation(row, of_column, to_column, distribution_dict):
    
    # if to_column has missing value, impute based on distribution of of_column
    if pd.isnull(row[to_column]):
        fix_value = row[of_column]
        distribution = distribution_dict.get(fix_value, None)
        if distribution is not None:
            return np.random.choice(distribution[to_column], p=distribution['Probability'])
    return row[to_column]

In [240]:
beds_distribution_dict = {value: calc_distribution(value, 'beds', 'bedrooms', listings) 
                          for value in listings['beds'].dropna().unique()}
print(beds_distribution_dict)

listings['bedrooms'] = listings.apply(
     lambda row: distribution_imputation(row, 'beds', 'bedrooms', beds_distribution_dict), axis=1)

{6.0:    bedrooms  Probability
0       3.0     0.362963
1       2.0     0.288889
2       4.0     0.214815
3       1.0     0.066667
4       5.0     0.037037
5       6.0     0.022222
6       7.0     0.007407, 2.0:    bedrooms  Probability
0       1.0     0.612294
1       2.0     0.369797
2       0.0     0.015005
3       3.0     0.002904, 3.0:    bedrooms  Probability
0       2.0     0.627790
1       1.0     0.225342
2       3.0     0.138949
3       0.0     0.005040
4       4.0     0.002880, 1.0:    bedrooms  Probability
0       1.0     0.947175
1       0.0     0.027102
2       2.0     0.020211
3       3.0     0.004134
4       7.0     0.000919
5       4.0     0.000459, 4.0:    bedrooms  Probability
0       2.0     0.537772
1       3.0     0.288092
2       1.0     0.115237
3       4.0     0.057618
4       0.0     0.001280, 5.0:    bedrooms  Probability
0       3.0     0.467153
1       2.0     0.317518
2       4.0     0.135036
3       1.0     0.047445
4       5.0     0.032847, 7.0:    bedrooms  Probability
0       3.0     0.358974
1       4.0     0.230769
2       2.0     0.179487
3       5.0     0.179487
4       7.0     0.025641
5       6.0     0.025641, 0.0:    bedrooms  Probability
0       1.0     0.704545
1       2.0     0.204545
2       3.0     0.045455
3       0.0     0.022727
4       5.0     0.011364
5       4.0     0.011364, 8.0:    bedrooms  Probability
0       3.0     0.347826
1       4.0     0.347826
2       5.0     0.130435
3       2.0     0.086957
4       6.0     0.086957, 9.0:    bedrooms  Probability
0       3.0     0.315789
1       4.0     0.210526
2       6.0     0.210526
3       5.0     0.157895
4       2.0     0.052632
5       1.0     0.052632, 12.0:    bedrooms  Probability
0      14.0     0.285714
1       7.0     0.285714
2       5.0     0.142857
3       4.0     0.142857
4       6.0     0.142857, 11.0:    bedrooms  Probability
0       2.0          0.5
1      11.0          0.5, 13.0:    bedrooms  Probability
0       7.0          0.5
1       4.0          0.5, 10.0:    bedrooms  Probability
0       7.0         0.50
1       6.0         0.25
2       8.0         0.25, 15.0:    bedrooms  Probability
0       5.0          1.0}

### Bathrooms

- On the Airbnb web-site, the bathrooms field has evolved from a number (`bathrooms`) to a textual description (`bathrooms_text`). For older scrapes, `bathrooms` is used."

In [241]:
missing_df = missing_info(listings, 'id', 'column', True)
missing_df

,column,dtype,num_missing,percent_missing,affected_row_ids
0,accommodates,int64,0,0.00,[]
1,amenities,object,0,0.00,[]
2,availability_30,int64,0,0.00,[]
3,availability_365,int64,0,0.00,[]
4,availability_60,int64,0,0.00,[]
...,...,...,...,...,...
67,review_scores_value,float64,740,9.52,"[1482860, 2014854, 3118010, 6782983, 7018697, ..."
68,reviews_per_month,float64,740,9.52,"[1482860, 2014854, 3118010, 6782983, 7018697, ..."
69,room_type,object,0,0.00,[]
70,scrape_id,int64,0,0.00,[]
71,source,object,0,0.00,[]

In [242]:
listings[['bathrooms', 'bathrooms_text']].head()

   bathrooms  bathrooms_text
0        2.0         2 baths
1        1.0  1 private bath
2        2.0         2 baths
3        1.0  1 private bath
4        1.0          1 bath

In [243]:
listings[['bathrooms_num', 'bathrooms_type']] = listings['bathrooms_text'].str.split(' ', n=1, expand=True)
listings['bathrooms_num'] = pd.to_numeric(listings['bathrooms_num'], errors='coerce')
listings[['bathrooms', 'bathrooms_text', 'bathrooms_num', 'bathrooms_type']].head()

   bathrooms  bathrooms_text  bathrooms_num bathrooms_type
0        2.0         2 baths            2.0          baths
1        1.0  1 private bath            1.0   private bath
2        2.0         2 baths            2.0          baths
3        1.0  1 private bath            1.0   private bath
4        1.0          1 bath            1.0           bath

In [244]:
print(listings['bathrooms_type'].unique())

['baths' 'private bath' 'bath' 'shared bath' 'shared baths' 'half-bath'
 nan None]

In [250]:
print(listings['bathrooms_text'].unique())

['2 baths' '1 private bath' '1 bath' '1 shared bath' '1.5 baths'
 '7 shared baths' '4 baths' 'Shared half-bath' '3 baths' '2.5 baths' nan
 '5 baths' '0 baths' '2 shared baths' '4.5 baths' 'Half-bath'
 '1.5 shared baths' '3 shared baths' '6 baths' '3.5 baths'
 '0 shared baths' '3.5 shared baths' '8 baths' '5.5 baths' '6.5 baths'
 '11 baths' '18 baths' '2.5 shared baths' '7.5 baths' '7 baths'
 'Private half-bath' '5 shared baths' '17 baths' '20 baths']

In [245]:
# show rows where bathroom and bathrooms_num differ
filtered_listings = listings[(listings['bathrooms_num'] != listings['bathrooms'])]
filtered_listings[['bathrooms', 'bathrooms_text', 'bathrooms_num', 'bathrooms_type']].head()

    bathrooms    bathrooms_text  bathrooms_num bathrooms_type
19        NaN    7 shared baths            7.0   shared baths
45        0.5  Shared half-bath            NaN      half-bath
46        NaN            1 bath            1.0           bath
54        NaN           2 baths            2.0          baths
62        0.5  Shared half-bath            NaN      half-bath

In [246]:
listings['bathrooms'] = listings['bathrooms_num'].combine_first(listings['bathrooms'])
listings = listings.drop('bathrooms_num', axis=1)

In [247]:
filtered_listings = listings[listings['bathrooms'].isnull()]
filtered_listings[['bathrooms', 'bathrooms_text', 'bathrooms_type']].head()

      bathrooms    bathrooms_text bathrooms_type
236         NaN               NaN            NaN
609         NaN  Shared half-bath      half-bath
3853        NaN         Half-bath           None
5878        NaN               NaN            NaN
5973        NaN               NaN            NaN

In [248]:
bathroom_row_ids = missing_df[missing_df['column'] == 'bathroom']['affected_row_ids'].values[0]
bathroom_text_row_ids = missing_df[missing_df['column'] == 'bathroom_text']['affected_row_ids'].values[0]
shared_ids = shared_values(bathroom_row_ids, bathroom_text_row_ids)
length = len(shared_ids)
length, (length/listings.shape[0])*100

IndexError: index 0 is out of bounds for axis 0 with size 0

##

### Host stuff

In [249]:
missing_df = missing_info(listings, 'id', 'column', True)
missing_df

,column,dtype,num_missing,percent_missing,affected_row_ids
0,accommodates,int64,0,0.00,[]
1,amenities,object,0,0.00,[]
2,availability_30,int64,0,0.00,[]
3,availability_365,int64,0,0.00,[]
4,availability_60,int64,0,0.00,[]
...,...,...,...,...,...
68,review_scores_value,float64,740,9.52,"[1482860, 2014854, 3118010, 6782983, 7018697, ..."
69,reviews_per_month,float64,740,9.52,"[1482860, 2014854, 3118010, 6782983, 7018697, ..."
70,room_type,object,0,0.00,[]
71,scrape_id,int64,0,0.00,[]
72,source,object,0,0.00,[]

### Redunce listings to the columns I need

In [ ]:
textData_columns = [
]

imageData_columns = ['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'availability_eoy',
       'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'
]

tabularData_columns = ['id', 'host_id', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'availability_eoy',
       'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month']

spatialData_columns = ['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'availability_eoy',
       'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'
]